name: "BedWars1058-Sponge"
main: "club.mher.sponge.Sponge"

version: "${project.version}"
author: "Mher Zaqaryan"

description: "BedWars1058 Sponge addon that plays an effect when placing a sponge."
api-version: "1.13"

softdepend:
  - "BedWars1058"